// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

//a http request as RPC
//forward by the api handler
type Request struct {
	Method               string           `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Get                  map[string]*Pair `protobuf:"bytes,4,rep,name=get,proto3" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Post                 map[string]*Pair `protobuf:"bytes,5,rep,name=post,proto3" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Url                  string           `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

//a http response as RPC
//expected response for the api handler
type Resposne struct {
	StatusCode           int32            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Resposne) Reset()         { *m = Resposne{} }
func (m *Resposne) String() string { return proto.CompactTextString(m) }
func (*Resposne) ProtoMessage()    {}
func (*Resposne) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *Resposne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resposne.Unmarshal(m, b)
}
func (m *Resposne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resposne.Marshal(b, m, deterministic)
}
func (m *Resposne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resposne.Merge(m, src)
}
func (m *Resposne) XXX_Size() int {
	return xxx_messageInfo_Resposne.Size(m)
}
func (m *Resposne) XXX_DiscardUnknown() {
	xxx_messageInfo_Resposne.DiscardUnknown(m)
}

var xxx_messageInfo_Resposne proto.InternalMessageInfo

func (m *Resposne) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Resposne) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Resposne) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

//a http event as RPC
//forwarded by the event handler
type Event struct {
	//e.g login
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//uuid
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	//unix timestamp of event
	Timestamp int64            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Header    map[string]*Pair `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//the event data
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "proto.Pair")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterMapType((map[string]*Pair)(nil), "proto.Request.GetEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "proto.Request.HeaderEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "proto.Request.PostEntry")
	proto.RegisterType((*Resposne)(nil), "proto.Resposne")
	proto.RegisterMapType((map[string]*Pair)(nil), "proto.Resposne.HeaderEntry")
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterMapType((map[string]*Pair)(nil), "proto.Event.HeaderEntry")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x5e, 0x3b, 0x69, 0x26, 0x52, 0x8b, 0xe6, 0x00, 0xab, 0x80, 0x50, 0xf0, 0x29, 0x95,
	0x50, 0x5a, 0xb9, 0x1c, 0x10, 0x47, 0x42, 0x0a, 0xc7, 0x6a, 0xff, 0x60, 0x2b, 0x8f, 0x88, 0x85,
	0x9d, 0x35, 0xde, 0x75, 0x45, 0xbe, 0xad, 0x1f, 0xc2, 0xef, 0xa0, 0x1d, 0x6f, 0xdd, 0x36, 0x2a,
	0x12, 0xaa, 0x72, 0xf2, 0xf3, 0xec, 0x9b, 0xb7, 0x6f, 0xde, 0x0e, 0x9c, 0x34, 0xad, 0x71, 0xe6,
	0x4c, 0x37, 0xe5, 0x92, 0x11, 0xa6, 0xfc, 0xc9, 0xce, 0x21, 0xb9, 0xd2, 0x65, 0x8b, 0x2f, 0x41,
	0xfc, 0xa4, 0x9d, 0x8c, 0xe6, 0xd1, 0x62, 0xa2, 0x3c, 0xc4, 0x57, 0x30, 0xba, 0xd1, 0x55, 0x47,
	0x56, 0xc6, 0x73, 0xb1, 0x98, 0xa8, 0xf0, 0x97, 0xdd, 0x0a, 0x18, 0x2b, 0xfa, 0xd5, 0x91, 0x75,
	0x9e, 0x53, 0x93, 0xdb, 0x98, 0x22, 0x34, 0x86, 0x3f, 0x44, 0x48, 0x1a, 0xed, 0x36, 0x32, 0xe6,
	0x2a, 0x63, 0xcc, 0x61, 0xb4, 0x21, 0x5d, 0x50, 0x2b, 0xc5, 0x5c, 0x2c, 0xa6, 0xf9, 0xac, 0x37,
	0xb2, 0x0c, 0x5a, 0xcb, 0xef, 0x7c, 0xb8, 0xde, 0xba, 0x76, 0xa7, 0x02, 0x13, 0x4f, 0x41, 0xfc,
	0x20, 0x27, 0x13, 0x6e, 0x78, 0xbd, 0xd7, 0xf0, 0x8d, 0x5c, 0xcf, 0xf6, 0x1c, 0xfc, 0x00, 0x49,
	0x63, 0xac, 0x93, 0x29, 0x73, 0xe5, 0x1e, 0xf7, 0xca, 0xd8, 0x40, 0x66, 0x96, 0x37, 0x78, 0x6d,
	0x8a, 0x9d, 0x1c, 0xf5, 0x06, 0x3d, 0xf6, 0x11, 0x74, 0x6d, 0x25, 0xc7, 0x7d, 0x04, 0x5d, 0x5b,
	0xcd, 0x2e, 0x61, 0xfa, 0xc0, 0xd5, 0x13, 0x19, 0xbd, 0x87, 0x94, 0x53, 0xe1, 0x41, 0xa7, 0xf9,
	0x34, 0xdc, 0xea, 0x13, 0x55, 0xfd, 0xc9, 0xe7, 0xf8, 0x53, 0x34, 0x5b, 0xc1, 0xd1, 0x9d, 0xd9,
	0xe7, 0x8b, 0x7c, 0x85, 0xc9, 0x30, 0xc5, 0xb3, 0x55, 0xb2, 0xdb, 0x08, 0x8e, 0x14, 0xd9, 0xc6,
	0xd8, 0x2d, 0xe1, 0x3b, 0x00, 0xeb, 0xb4, 0xeb, 0xec, 0xca, 0x14, 0xc4, 0x62, 0xa9, 0x7a, 0x50,
	0xc1, 0x8b, 0xe1, 0xc9, 0x62, 0x4e, 0xf5, 0xcd, 0x90, 0x6a, 0x2f, 0xf0, 0xe4, 0x9b, 0xdd, 0x45,
	0x2b, 0xee, 0xa3, 0x3d, 0x54, 0x90, 0xd9, 0x9f, 0x08, 0xd2, 0xf5, 0x0d, 0x6d, 0xf9, 0x01, 0xb7,
	0xba, 0xa6, 0xa0, 0xc1, 0x18, 0x8f, 0x21, 0x2e, 0x8b, 0xb0, 0x73, 0x71, 0x59, 0xe0, 0x5b, 0x98,
	0xb8, 0xb2, 0x26, 0xeb, 0x74, 0xdd, 0xb0, 0x1d, 0xa1, 0xee, 0x0b, 0x78, 0x3e, 0x0c, 0x97, 0x3c,
	0x5a, 0x19, 0xd6, 0xff, 0xd7, 0x64, 0x85, 0x76, 0x5a, 0xa6, 0xfd, 0x9d, 0x1e, 0x1f, 0x6a, 0xb2,
	0xfc, 0x23, 0x8c, 0xd7, 0xbf, 0x75, 0xdd, 0x54, 0x84, 0xa7, 0x90, 0xac, 0x74, 0x55, 0xe1, 0xf1,
	0xe3, 0x1d, 0x9e, 0x9d, 0xec, 0xa5, 0x9f, 0xbd, 0xc8, 0xcf, 0x40, 0x5c, 0x1a, 0x83, 0x0b, 0x10,
	0x5f, 0x74, 0xfb, 0x1f, 0x0d, 0xd7, 0x23, 0xae, 0x5c, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x60,
	0xd0, 0xff, 0xdf, 0x0f, 0x04, 0x00, 0x00,
}
